version: "3"

services:
  db:
    container_name: postgres
    image: postgres:12.3-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
